#!/usr/bin/env python3
"""Sweep matcher thresholds and render calibration evidence (#691).

Reads the fixed ground-truth sample from the public golden/nearmiss corpora
(via :mod:`cauterule.replay.calibration`) and reports precision/recall at each
threshold so the constants in ``matcher.py`` have committed provenance.

Usage:
    python scripts/calibrate_thresholds.py
    python scripts/calibrate_thresholds.py --output docs/field-test/v0.3.0/threshold-calibration.md
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cauterule.replay.calibration import (
    DEFAULT_PUBLIC_ROOT,
    CalibrationMetrics,
    sweep_thresholds,
)
from cauterule.replay.matcher import (
    OMLX_NEARMISS_THRESHOLD,
    OMLX_THRESHOLD,
    STRATEGY_THRESHOLDS,
)


def render_markdown(rows: list[CalibrationMetrics], public_root: Path) -> str:
    """Render the sweep as a markdown evidence table."""
    try:
        display_root = os.path.relpath(public_root)
    except ValueError:
        display_root = str(public_root)
    lines = [
        "# Matcher Threshold Calibration (v0.3.0)",
        "",
        "<!-- generated by scripts/calibrate_thresholds.py, do not hand-edit -->",
        "",
        f"Generated: {datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"Sample: `{display_root}/golden` (positives) + `{display_root}/nearmiss` "
        "(negatives, with cross-scenario golden pairs).",
        "",
        "Metrics use the production `rule_matches()` matcher, so domain/context",
        "filters are applied exactly as in replay.",
        "",
        "| Threshold | Precision | Recall | TP | FP | FN | TN |",
        "|-----------|-----------|--------|----|----|----|----|",
    ]
    for m in rows:
        lines.append(
            f"| {m.threshold:.2f} | {m.precision:.3f} | {m.recall:.3f} "
            f"| {m.tp} | {m.fp} | {m.fn} | {m.tn} |"
        )
    lines += [
        "",
        "## Shipped thresholds",
        "",
        "| Constant | Value |",
        "|----------|-------|",
        f"| `STRATEGY_THRESHOLDS['strict']` | {STRATEGY_THRESHOLDS['strict']:.2f} |",
        f"| `STRATEGY_THRESHOLDS['loose']` | {STRATEGY_THRESHOLDS['loose']:.2f} |",
        f"| `STRATEGY_THRESHOLDS['semantic']` | {STRATEGY_THRESHOLDS['semantic']:.2f} |",
        f"| `STRATEGY_THRESHOLDS['transfer']` | {STRATEGY_THRESHOLDS['transfer']:.2f} |",
        f"| `OMLX_THRESHOLD` | {OMLX_THRESHOLD:.2f} |",
        f"| `OMLX_NEARMISS_THRESHOLD` | {OMLX_NEARMISS_THRESHOLD:.2f} |",
        "",
        "The regression test `tests/replay/test_threshold_calibration.py` asserts",
        "precision >= 0.90 and recall >= 0.45 at the shipped thresholds. Re-run",
        "this script after any change to aliases, distinctive phrases, domain",
        "groups, or thresholds and update the committed baseline if intentional.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    """Sweep thresholds, print the table, and optionally write the evidence doc."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--public-root", type=Path, default=DEFAULT_PUBLIC_ROOT)
    parser.add_argument("--start", type=float, default=0.50)
    parser.add_argument("--stop", type=float, default=0.80)
    parser.add_argument("--step", type=float, default=0.05)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    rows = sweep_thresholds(start=args.start, stop=args.stop, step=args.step)
    rendered = render_markdown(rows, Path(args.public_root))
    print(rendered)
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
        print(f"\n[calibrate] wrote {args.output}")


if __name__ == "__main__":
    main()
