#!/usr/bin/env python3
"""Single source of truth for v0.3.0 field-test result tables (#686).

Reads ``field-test/results/<version>/<corpus>/<model>/<date>/results.jsonl``
(the raw sweep records) and renders the numeric tables that were previously
hand-typed into the field-test docs.  The hand-authored narrative stays in
``FIELD_TEST_REPORT.md``; the generated tables live in
``docs/field-test/v0.3.0/generated-results.md``.

Usage:
    python scripts/generate_field_test_report.py
    python scripts/generate_field_test_report.py --check   # exit 1 on drift
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cauterule.stats import rate_with_ci

_REPO = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS_ROOT = _REPO / "field-test" / "results" / "0.3.0"
DEFAULT_OUTPUT = _REPO / "docs" / "field-test" / "v0.3.0" / "generated-results.md"

_SENTINEL = "<!-- generated by scripts/generate_field_test_report.py, do not hand-edit -->"

# Friendly model labels (directory name -> report name).
_MODEL_LABELS: dict[str, str] = {
    "omlx-openai-Llama-3.2-3B-Instruct-4bit": "Llama-3.2-3B (OMLX)",
    "omlx-openai-Qwen3-4B-Instruct-2507-4bit": "Qwen3-4B (OMLX)",
    "openai-openai_gpt-4o-mini": "gpt-4o-mini",
    "openai-meta-llama_llama-3.1-8b-instruct": "llama-3.1-8b",
}


@dataclass(frozen=True)
class RunSummary:
    """Aggregated outcome for one (corpus, model) sweep run."""

    corpus: str
    model: str
    model_label: str
    total: int
    done: int
    gate_dropped: int
    passed: int
    failed: int
    inconclusive: int

    @property
    def pass_rate(self) -> dict[str, float | int]:
        """Pass rate over decided (pass+fail) trajectories, with Wilson CI."""
        return rate_with_ci(self.passed, self.passed + self.failed)


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped:
            records.append(json.loads(stripped))
    return records


def summarize_records(
    records: list[dict[str, Any]], *, corpus: str, model: str, model_label: str
) -> RunSummary:
    """Aggregate raw result records into a :class:`RunSummary`."""
    done = [r for r in records if r.get("status") == "done"]
    gate_dropped = [r for r in records if r.get("status") == "gate_dropped"]

    def verdict(record: dict[str, Any]) -> str | None:
        best = record.get("best") or {}
        return best.get("verdict") if isinstance(best, dict) else None

    passed = sum(1 for r in done if verdict(r) == "pass")
    failed = sum(1 for r in done if verdict(r) == "fail")
    inconclusive = sum(1 for r in done if verdict(r) == "inconclusive")
    return RunSummary(
        corpus=corpus,
        model=model,
        model_label=model_label,
        total=len(records),
        done=len(done),
        gate_dropped=len(gate_dropped),
        passed=passed,
        failed=failed,
        inconclusive=inconclusive,
    )


def _run_meta(run_dir: Path) -> dict[str, Any]:
    summary = run_dir / "summary.json"
    if summary.exists():
        try:
            return json.loads(summary.read_text(encoding="utf-8")).get("meta") or {}
        except json.JSONDecodeError:
            return {}
    return {}


def load_runs(results_root: str | Path | None = None) -> list[RunSummary]:
    """Load and aggregate every sweep run under *results_root*."""
    root = Path(results_root) if results_root is not None else DEFAULT_RESULTS_ROOT
    runs: list[RunSummary] = []
    for results_file in sorted(root.glob("*/*/*/results.jsonl")):
        parts = results_file.relative_to(root).parts
        corpus_dir, model_dir = parts[0], parts[1]
        meta = _run_meta(results_file.parent)
        corpus = str(meta.get("corpus_type") or corpus_dir)
        model_label = _MODEL_LABELS.get(model_dir, model_dir)
        runs.append(
            summarize_records(
                _read_jsonl(results_file),
                corpus=corpus,
                model=model_dir,
                model_label=model_label,
            )
        )
    return runs


def model_totals(runs: list[RunSummary]) -> dict[str, int]:
    """Sum trajectory counts per model label."""
    totals: dict[str, int] = {}
    for run in runs:
        totals[run.model_label] = totals.get(run.model_label, 0) + run.total
    return totals


def render_markdown(runs: list[RunSummary]) -> str:
    """Render the generated results tables as markdown."""
    totals = model_totals(runs)
    grand_total = sum(totals.values())
    lines = [
        "# Field-Test Results (generated) — v0.3.0",
        "",
        _SENTINEL,
        "",
        f"Generated: {datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        "",
        "Numeric tables derived from `field-test/results/0.3.0/**/results.jsonl`.",
        "Do not hand-edit; re-run `scripts/generate_field_test_report.py`.",
        "",
        "## Model totals",
        "",
        "| Model | Trajectories |",
        "|-------|--------------|",
    ]
    for label in sorted(totals):
        lines.append(f"| {label} | {totals[label]:,} |")
    lines += [f"| **Total** | **{grand_total:,}** |", ""]

    for model_label in sorted({r.model_label for r in runs}):
        model_runs = sorted(
            (r for r in runs if r.model_label == model_label), key=lambda r: r.corpus
        )
        lines += [
            f"## {model_label}",
            "",
            "| Corpus | Traj | Pass | Fail | Inconcl. | Gate-dropped | Pass rate [95% CI] |",
            "|--------|------|------|------|----------|--------------|--------------------|",
        ]
        for run in model_runs:
            ci = run.pass_rate
            lines.append(
                f"| {run.corpus} | {run.total} | {run.passed} | {run.failed} "
                f"| {run.inconclusive} | {run.gate_dropped} "
                f"| {ci['rate']:.0%} [{ci['ci_low']:.0%}-{ci['ci_high']:.0%}] (n={ci['n']}) |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    """Generate the results document, or check it for drift with ``--check``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-root", type=Path, default=DEFAULT_RESULTS_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed output differs from a fresh render.",
    )
    args = parser.parse_args()

    generated = render_markdown(load_runs(args.results_root))
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""

        # Ignore the timestamp line when diffing so checks are date-stable.
        def strip_timestamp(text: str) -> str:
            return "\n".join(
                line for line in text.splitlines() if not line.startswith("Generated:")
            )

        if strip_timestamp(generated) != strip_timestamp(current):
            print(f"[drift] {args.output} is out of date — re-run the generator.")
            raise SystemExit(1)
        print(f"[ok] {args.output} is up to date.")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    print(f"[generate] wrote {args.output}")


if __name__ == "__main__":
    main()
